apiVersion: sonataflow.org/v1alpha08
kind: SonataFlow
metadata:
  annotations:
    sonataflow.org/description: Simple Order
    sonataflow.org/expressionLang: jq
    sonataflow.org/profile: preview
    sonataflow.org/version: "0.3"
  creationTimestamp: null
  labels:
    app: simple-order
    sonataflow.org/workflow-app: simple-order
  name: simple-order
  namespace: swf-prod
spec:
  flow:
    events:
    - correlation:
      - contextAttributeName: orderid
      dataOnly: true
      kind: consumed
      name: New Order Event
      source: client
      type: newOrderEvent
    - correlation:
      - contextAttributeName: orderid
      dataOnly: true
      kind: consumed
      name: Inventory Result Event
      source: client
      type: inventoryResult
    functions:
    - name: printMessage
      operation: sysout
      type: custom
    start:
      stateName: Order Received
    states:
    - exclusive: true
      name: Order Received
      onEvents:
      - actionMode: sequential
        eventDataFilter:
          useData: true
        eventRefs:
        - New Order Event
      transition:
        nextState: Check Inventory
      type: event
    - action:
        actionDataFilter:
          useResults: true
        functionRef:
          arguments:
            message: Inventory Callback
          invoke: sync
          refName: printMessage
        name: printAction
      eventRef: Inventory Result Event
      name: Check Inventory
      timeouts:
        stateExecTimeout:
          total: PT2M
      transition:
        nextState: Inventory Result
      type: callback
    - actionMode: sequential
      actions:
      - actionDataFilter:
          useResults: true
        functionRef:
          arguments:
            message: Inventory Result Received
          invoke: sync
          refName: printMessage
        name: printAction
      end:
        terminate: true
      name: Inventory Result
      type: operation
  podTemplate:
    container:
      resources: {}
  resources: {}
status:
  address: {}
  lastTimeRecoverAttempt: null
